import { PublicNavbar } from '@/components/public-navbar';
import { PublicFooter } from '@/components/public-footer';
import { AlertTriangle } from 'lucide-react';

export const metadata = { title: 'Disclaimer — MA Finance Hub' };

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#F5F0E8]">
      <PublicNavbar />

      <section className="mx-auto max-w-4xl px-6 py-16">
        <div className="flex items-center gap-3">
          <AlertTriangle className="h-8 w-8 text-[#D4A854]" />
          <h1 className="text-4xl font-extrabold text-[#5C4033]">Disclaimer</h1>
        </div>
        <p className="mt-2 text-sm text-[#8B7355]">Last updated: March 31, 2026</p>

        <div className="mt-8 space-y-6 text-[#5C4033]">
          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Not Financial Advice</h2>
            <p className="mt-2 text-[#8B7355]">
              MA Finance Hub is a business management software tool. Nothing in
              this application constitutes financial, tax, legal, or accounting
              advice. You should consult a licensed CPA, tax advisor, or
              attorney for guidance specific to your situation.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Tax Calculations</h2>
            <p className="mt-2 text-[#8B7355]">
              Payroll tax calculations, sales tax estimates, and any other tax
              computations provided by MA Finance Hub are approximations based
              on simplified federal and state tax tables. These calculations may
              not reflect your exact tax liability. Tax laws change frequently,
              and the software may not reflect the most recent legislation.
              Always verify tax amounts with a licensed tax professional before
              filing any returns.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Financial Reports</h2>
            <p className="mt-2 text-[#8B7355]">
              Financial reports generated by this software — including but not
              limited to the Balance Sheet, Income Statement, and Cash Flow
              Statement — are based entirely on data entered by the user. These
              reports have not been audited, reviewed, or compiled by a
              Certified Public Accountant. They should not be relied upon as
              audited financial statements.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Legal Compliance</h2>
            <p className="mt-2 text-[#8B7355]">
              While MA Finance Hub is designed to support GAAP-compliant
              accounting practices, the software does not guarantee compliance
              with any specific regulatory framework, including but not limited
              to GAAP, IFRS, IRS regulations, or state-specific requirements.
              It is the user&apos;s responsibility to ensure that their use of
              the software complies with all applicable laws and regulations.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Data Accuracy</h2>
            <p className="mt-2 text-[#8B7355]">
              MA Intelligent Systems LLC makes no representations or warranties
              regarding the accuracy, completeness, or reliability of any
              calculations, reports, or data produced by the software. The
              accuracy of outputs depends on the accuracy of user-provided
              inputs. We are not liable for errors, omissions, or financial
              losses resulting from the use of this software.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Third-Party Integrations</h2>
            <p className="mt-2 text-[#8B7355]">
              The Service may integrate with third-party services such as banks,
              payment processors, and tax authorities. MA Intelligent Systems
              LLC is not responsible for the accuracy, availability, or security
              of these third-party services.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Limitation of Liability</h2>
            <p className="mt-2 text-[#8B7355]">
              In no event shall MA Intelligent Systems LLC, its officers,
              directors, employees, or agents be liable for any indirect,
              incidental, special, consequential, or punitive damages arising
              out of or relating to the use of this software. Your use of MA
              Finance Hub is at your sole risk.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Changes to This Disclaimer</h2>
            <p className="mt-2 text-[#8B7355]">
              We reserve the right to update this disclaimer at any time.
              Continued use of the Service after changes constitutes acceptance
              of the updated terms.
            </p>
          </div>

          <div className="rounded-xl border border-[#E8DCC8] bg-white p-6">
            <h2 className="text-xl font-bold">Contact</h2>
            <p className="mt-2 text-[#8B7355]">
              If you have questions about this disclaimer, contact us at{' '}
              <a href="mailto:support@maishq.com" className="text-[#2D6A4F] hover:underline">
                support@maishq.com
              </a>.
            </p>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
