import { Controller, Get, Post, Body, UseGuards, BadRequestException } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard, IdentityGuard, RolesGuard, CurrentPrincipal, Roles } from '../auth';
import { AuthenticatedPrincipal } from '../auth/interfaces';
import { TenantContextService } from '../auth/tenant-context.service';
import { AuditService } from '../auth/audit.service';
import { EntitlementGuard, RequiresEntitlement } from '../entitlements';
import { JournalService } from '../journal/journal.service';
import { PostingRulesService, EventPayload } from './posting-rules.service';
import { IsString, IsNotEmpty, IsNumber, IsInt, IsOptional, Min, MaxLength } from 'class-validator';

class ProcessEventDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  event_type!: string;

  @IsNumber({ maxDecimalPlaces: 4 })
  @Min(0)
  amount!: number;

  @IsInt()
  @Min(1)
  fiscal_period_id!: number;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  reference?: string;

  @IsOptional()
  @IsString()
  @MaxLength(255)
  idempotency_key?: string;
}

@ApiTags('Posting Rules')
@ApiBearerAuth()
@Controller('posting-rules')
@UseGuards(JwtAuthGuard, IdentityGuard, RolesGuard, EntitlementGuard)
@RequiresEntitlement('feature.journal')
export class PostingRulesController {
  constructor(
    private readonly tenantContext: TenantContextService,
    private readonly postingRulesService: PostingRulesService,
    private readonly journalService: JournalService,
    private readonly audit: AuditService,
  ) {}

  @Get()
  @Roles('owner', 'admin', 'manager')
  async listRules(@CurrentPrincipal() p: AuthenticatedPrincipal) {
    return this.tenantContext.runInTenantContext(p.tenantId, p.sub, (trx) =>
      trx('posting_rules').select('id', 'event_type', 'name', 'description', 'is_active'),
    );
  }

  @Post('process')
  @Roles('owner', 'admin', 'manager')
  async processEvent(@CurrentPrincipal() p: AuthenticatedPrincipal, @Body() dto: ProcessEventDto) {
    return this.tenantContext.runInTenantContext(p.tenantId, p.sub, async (trx) => {
      // Idempotency: check if this event was already processed
      if (dto.idempotency_key) {
        const existing = await trx('journal_entries')
          .where({ reference: dto.idempotency_key })
          .first() as Record<string, unknown> | undefined;
        if (existing) {
          const entry = await this.journalService.findOne(trx, Number(existing.id));
          return { processed: 0, duplicate: true, existingEntry: entry };
        }
      }

      const payload: EventPayload = { event_type: dto.event_type, amount: dto.amount };
      const rules = await this.postingRulesService.findMatchingRules(trx, dto.event_type);

      if (rules.length === 0) {
        throw new BadRequestException(`No active posting rules for event type '${dto.event_type}'`);
      }

      const results = [];
      for (const rule of rules) {
        const lines = this.postingRulesService.executeRule(rule, payload);

        const entry = await this.journalService.create(trx, {
          tenant_id: p.tenantId,
          fiscal_period_id: dto.fiscal_period_id,
          reference: dto.idempotency_key || dto.reference || `AUTO-${dto.event_type}`,
          memo: `Generated by posting rule: ${rule.ruleName}`,
          lines,
        });

        await this.audit.log(trx, {
          tenant_id: p.tenantId,
          actor_subject: p.sub,
          action: 'posting_rule_execute',
          entity: 'posting_rules',
          entity_id: String(rule.ruleId),
          metadata: {
            event_type: dto.event_type,
            journal_entry_id: entry.id,
            idempotency_key: dto.idempotency_key || null,
          },
        });

        results.push({ rule: rule.ruleName, journalEntry: entry });
      }

      return { processed: results.length, duplicate: false, entries: results };
    });
  }
}
